### ISSUE TITLE
imgui_impl_glfw.cpp defines GLFW_EXPOSE_NATIVE_X11 on Wayland system

### ISSUE THREAD

**Issue by cm-1** [ocornut/imgui#9225]
### Version/Branch of Dear ImGui:

Version 1.92.5

### Back-ends:

imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp

### Compiler, OS:

Linux + clang

### Full config/build information:

```cpp
Dear ImGui 1.92.5 (19250)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=202002
define: __linux__
define: __GNUC__=4
define: __clang_version__=21.1.8 (Fedora 21.1.8-4.fc43)
IM_ASSERT: runs expression: OK. expand size: OK
--------------------------------
io.BackendPlatformName: imgui_impl_glfw (3400)
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000003
 NavEnableKeyboard
 NavEnableGamepad
io.ConfigNavCaptureKeyboard
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000001E
 HasMouseCursors
 HasSetMousePos
 RendererHasVtxOffset
 RendererHasTextures
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,128
io.Fonts->FontLoaderName: stb_truetype
io.DisplaySize: 1280.00,800.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

**imgui_impl_glfw.cpp Defines GLFW_EXPOSE_NATIVE_X11 on Wayland:**

When I run the newest version of ImGui+GLFW3 on Wayland, I get the following error:
```
build] [ 85%] Building CXX object <mycode>/thirdparty/imgui-1.92.5/backends/imgui_impl_glfw.cpp.o
[build] In file included from <mycode>/thirdparty/imgui-1.92.5/backends/imgui_impl_glfw.cpp:132:
[build] <mycode>/thirdparty/glfw-3.4/include/GLFW/glfw3native.h:119:12: fatal error: 'X11/extensions/Xrandr.h' file not found
[build]   119 |   #include <X11/extensions/Xrandr.h>
[build]       |            ^~~~~~~~~~~~~~~~~~~~~~~~~
[build] 1 error generated.
```
I'm on Wayland and while I could just install xrandr and be done with it, I'm still not sure this is intended/optimal behaviour.

The issue arises from the lines 117-133 in `imgui_impl_glfw.cpp`. If I comment out line 130, the `#define GLFW_EXPOSE_NATIVE_X11`, my program runs. 
```c++
#ifdef _WIN32
// <omitted WIN32 and APPLE lines here for conciseness>
#elif GLFW_HAS_X11_OR_WAYLAND
#ifndef GLFW_EXPOSE_NATIVE_X11      // for glfwGetX11Display(), glfwGetX11Window() on Freedesktop (Linux, BSD, etc.)
#define GLFW_EXPOSE_NATIVE_X11     // *If I comment out this line, my program runs!*
#endif
#include <GLFW/glfw3native.h>
#endif
```

This also seems to be an issue in 1.92.3, though things worked fine in 1.89.2. I haven't tested any other versions yet.

Is the `GLFW_EXPOSE_NATIVE_X11` definition, and thus an xrandr install,  _really_ needed for Wayland users? If not, is there a way to change this error source? I know my program runs fine when I comment it out, but I haven't had the chance to more extensively investigate what the consequences are.

Thanks!

### Minimal, Complete and Verifiable Example code:

```cpp
#include "imgui_impl_glfw.h"
#include <iostream>

int main()
{
    std::cout << "Sleeping!" << std::endl;
    ImGui_ImplGlfw_Sleep(1000);
    std::cout << "Done!" << std::endl;
    return 0;
}
```

**Comment by ocornut** [comment]
You can `#define IMGUI_IMPL_GLFW_DISABLE_X11`, see a07b2828ce89c2e10cfcf26450c0b0c3cc4a208f.

Since both Clang and GCC support has_include directive perhaps we should support that.
Can you try changing
```cpp
#if !defined(IMGUI_IMPL_GLFW_DISABLE_X11) && (defined(__linux__) || defined(__FreeBSD__) || defined(__OpenBSD__) || defined(__NetBSD__) || defined(__DragonFly__))
```
to
```cpp
#if !defined(IMGUI_IMPL_GLFW_DISABLE_X11) && (defined(__linux__) || defined(__FreeBSD__) || defined(__OpenBSD__) || defined(__NetBSD__) || defined(__DragonFly__)) && __has_include(<X11/extensions/Xrandr.h>)
```
?

**Comment by cm-1** [comment]
Thanks for the reply! I suppose I should have checked out master in addition to the latest release. Setting `#define IMGUI_IMPL_GLFW_DISABLE_X11` works, and leaving it undefined but making the line change with `__has_include` that you suggested also works.

**Comment by ocornut** [comment]
Thank you for trying both.
I have pushed 9f30044 however I am actually really hesitant to use `__has_include()` I find that it is risky in the sense that it tends to allow building backend with missing features without the user realizing it.
I might decide to backtrack on this and revert it and instead promote using e.g. `IMGUI_IMPL_GLFW_DISABLE_X11` to knowingly disable X11 features.
