### ISSUE TITLE
VS2008 fails to compile imgui due to use of undefined int64_t

### ISSUE THREAD

**Issue by idbrii** [ocornut/imgui#1184]
I'm using tag v1.50 and it looks like commit 4c25de950cfb1ef55aa2643b116a752aeba830b8 introduced a Win32 compile error. Fixing some clang warnings by using int64_t breaks compilation with VS2008 which doesn't provide stdint. See imgui.cpp:629:

	#if defined(_MSC_VER) && _MSC_VER <= 1500 // MSVC 2008 or earlier
	#include <stddef.h>     // intptr_t
	#else
	#include <stdint.h>     // intptr_t
	#endif

The assert modified in the above commit is [here]( https://github.com/ocornut/imgui/blob/v1.50/imgui.cpp#L2608) and it produces this error:

	..\..\imgui.cpp(2608) : error C2065: 'int64_t' : undeclared identifier
	..\..\imgui.cpp(2608) : error C2146: syntax error : missing ')' before identifier 'draw_list'
	..\..\imgui.cpp(2608) : error C2059: syntax error : ')'
	..\..\imgui.cpp(9867) : fatal error C1903: unable to recover from previous error(s); stopping compilation

I'm running the imgui/examples/sdl_opengl2_example/build_win32.bat (although I admit that I don't have the right version of SDL so I get other errors, but I think imgui.cpp should compile independently).

My compiler (VS2008 3.5 SP1):
Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 15.00.21022.08 for 80x86

This is an old compiler and I can get by with adding a typedef before the assert, so it's not a deal breaker.

**Comment by ocornut** [comment]
Does any other header with visual c++ include the type? Otherwise thats still pretty fixable its just tricky to get those tested in variety of compilers/versions.

**Comment by idbrii** [comment]
I don't think any MSVC header defines it. I see no int64_t in:
c:/Program Files/Microsoft SDKs/Windows/v6.0A/include/
c:/Program Files (x86)/Microsoft Visual Studio 9.0/VC/include/

[Random questions](https://stackoverflow.com/questions/5658021/whats-the-equivalent-of-int64-t-int-least16-t-uint8-t-in-visual-c-2008#) on the internet agree that it's missing from VS2008.

[Microsoft's Standard Types documentation](https://msdn.microsoft.com/en-us/library/323b6b3k(v=vs.90).aspx) doesn't list it, but it is listed in [more recent VS versions](https://msdn.microsoft.com/en-us/library/323b6b3k.aspx).

**Comment by paulsapps** [comment]
In MSVC 2015 its in C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\stdint.h

typedef long long          int64_t;

**Comment by ocornut** [comment]
Well I guess we should just remove that `int64_t` it's only used here and nowhere else, it was wrong of me to add it.

Now to find a type that works everywhere...
I'm surprised by http://en.cppreference.com/w/cpp/language/types says that `long long` being 64-bit at least is a C++11 guarantee?
@idbrii Does it works for you with `long long` ?

**Comment by ocornut** [comment]
Anyway, this discussion is misled: the assert can be expressed without a 64-bit types! Should be fixed now. Could you confirm @idbrii ?

**Comment by mikesart** [comment]
Hey @ocornut, this new assert:

```IM_ASSERT((draw_list->_VtxCurrentIdx >> (sizeof(ImDrawIdx)*8)) == 0);```

I'm using 32-bit indices so it's trying to right shift a 32-bit value by 32 bits, which will always be 0...

**Comment by ocornut** [comment]
@mikesart Yes that is the point here, the assert will currently never fail with 32-bit indices.
It is giving you a warning?

**Comment by mikesart** [comment]
Unfortunately, I believe that's undefined behavior and it's triggering an address sanitizer error:

src/imgui/imgui.cpp:2657:5: runtime error: shift exponent 32 is too large for 32-bit type 'unsigned int'
gpuvis: src/imgui/imgui.cpp:2657: void AddDrawListToRenderList(ImVector<ImDrawList*>&, ImDrawList*): Assertion `(draw_list->_VtxCurrentIdx >> (sizeof(uint32_t)*8)) == 0' failed.
Aborted

**Comment by ocornut** [comment]
OK I'll revert to the other method with an hopefully-portable way to define a 64-bit types.
You can comment the line for now.

**Comment by ocornut** [comment]
@mikesart Could you confirm that this work with your compiler?

```
#ifdef _MSC_VER
typedef unsigned __int64 ImU64;     // 64-bit unsigned integer
#else
typedef unsigned long long ImU64;   // 64-bit unsigned integer
#endif 
```
```
IM_ASSERT(((ImU64)draw_list->_VtxCurrentIdx >> (sizeof(ImDrawIdx)*8)) == 0);  // Too many vertices in same ImDrawList. See comment above.
```

**Comment by mikesart** [comment]
@ocornut Yes, that works. In case it comes up, I'm running gcc v6.3.0-18 on 64-bit Debian Stretch... Thanks much Omar.

**Comment by ocornut** [comment]
Pushed fix.

**Comment by mikesart** [comment]
Got it & it's working. Thanks Omar!

**Comment by idbrii** [comment]
Sorry for the slow reply. My original fix was `typedef long long int64_t;` but the a5e0210 fix also works for me on VS2008.
Thanks!
