### ISSUE TITLE
InputText in read-only mode renders opaque background, obscuring text in imgui_memory_editor

### ISSUE THREAD

**Issue by Dimoks** [ocornut/imgui#8714]
### Version/Branch of Dear ImGui:

afe20dc master

### Back-ends:

imgui_impl_glfw.cpp + imgui_impl_opengl2.cpp

### Compiler, OS:

MSYS2, gcc 15.1.0, Windows 10

### Details:

After updating Dear ImGui to a recent version (around commit afe20dc9 or later), a rendering issue occurs in imgui_memory_editor (v0.58 from ocornut/imgui_club) when used in read-only mode. Specifically, when a byte is selected in the hex area, the InputText widget used to display the byte value renders with an opaque background, which obscures the underlying byte text. This makes the selected byte unreadable until the selection is cleared (e.g., by clicking elsewhere, such as the footer).

The issue does not appear in earlier versions of ImGui. It seems related to changes in the rendering or styling of InputText in read-only mode.

Use imgui_memory_editor (v0.58) from ocornut/imgui_club with the latest ImGui (e.g., commit afe20dc9 or newer).
Set up a MemoryEditor instance in read-only mode and display some data.
Click on a byte in the hex area to select it.
Observe that the selected byte is obscured by the opaque background of the InputText widget.

### Screenshots/Video:

![Image](https://github.com/user-attachments/assets/808f8c79-f252-4fa6-8b47-692bdecf1cf7)

### Minimal, Complete and Verifiable Example code:

```cpp
#include <imgui_memory_editor.h>
...
MemoryEditor mem_edit;
mem_edit.ReadOnly = true;
ImGui::Begin("Example Bug");
mem_edit.DrawContents(raw_data.data(), raw_data.size());
ImGui::End();
```

**Comment by Dimoks** [comment]
In imgui_memory_editor.h you should replace
```cpp
#if defined(_MSC_VER) || defined(_UCRT)
#define _PRISizeT   "I"
#define ImSnprintf  _snprintf
#else
#define _PRISizeT   "z"
#define ImSnprintf  snprintf
#endif
```
by
```cpp
#if defined(_MSC_VER)
#define _PRISizeT   "I"
#define ImSnprintf  _snprintf
#else
#define _PRISizeT   "z"
#define ImSnprintf  snprintf
#endif
```

**Comment by ocornut** [comment]
Thanks for reporting. This is caused by b2c73596aeaf63b46b66a615ec02fce1b87f4248 (#8689)

> In imgui_memory_editor.h you should replace
> #if defined(_MSC_VER) || defined(_UCRT)

This seems unrelated. Can you explain?

**Comment by Dimoks** [comment]
```
imgui_memory_editor.h:560:53: error: 'I' flag used with '%X' gnu_scanf format [-Werror=format=]
  560 |             if (sscanf(AddrInputBuf, "%" _PRISizeT "X", &goto_addr) == 1)
      |                                                     ^
imgui_memory_editor.h:560:53: error: format '%X' expects argument of type 'unsigned int*', but argument 3 has type 'size_t*' {aka 'long long unsigned int*'} [-Werror=format=]
  560 |             if (sscanf(AddrInputBuf, "%" _PRISizeT "X", &goto_addr) == 1)
      |                                       ~~~~~~~~~~~~~~^   ~~~~~~~~~~
      |                                                     |   |
      |                                                     |   size_t* {aka long long unsigned int*}
      |                                                     unsigned int*
      |                                       %" _PRISizeT "llX
cc1plus.exe: all warnings being treated as errors
ninja: build stopped: subcommand failed.
```

**Comment by ocornut** [comment]
Fixed the main bug affecting memory_editor with 0dc2885. Nothing to do with opaque background, but memory editor replace the text buffer with latest byte value and that path was broken for read-only mode.

**Comment by ocornut** [comment]
Does using this block works with your compiler setup?

```cpp
#if defined(_MSC_VER) && !defined(snprintf)
#define ImSnprintf  _snprintf
#else
#define ImSnprintf  snprintf
#endif

#if defined(_MSC_VER) && !defined(__clang__)
#define _PRISizeT   "I"
#else
#define _PRISizeT   "z"
#endif
```
?

**Comment by Dimoks** [comment]
Yes, the following are selected:
#define ImSnprintf  snprintf
#define _PRISizeT   "z"

**Comment by ocornut** [comment]
Pushed that change to memory editor:
https://github.com/ocornut/imgui_club/commit/63e0ae5d0addd3237a25d569fa5aa674d0f794de
