### ISSUE TITLE
Compilation failure when compiling with -Werror

### ISSUE THREAD

**Issue by inodlite** [ocornut/imgui#2565]
**Version/Branch of Dear ImGui:**

Version: 1.70 (and latest master)
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_opengl3.cpp + imgui_impl_sdl.cpp
Compiler: GCC 9
Operating System: Fedora 30

**My Issue/Question:**

After updating from 1.68 to 1.70 compilation fails with the -Werror=class-memaccess errors. Here is a build log from example_sdl_opengl3:

>g++ -I../ -I../../ -g -Wall -Wformat -Werror -I../libs/gl3w -I../libs/gl3w `sdl2-config --cflags` -c -o imgui.o ../../imgui.cpp
In file included from ../../imgui.cpp:977:
../../imgui_internal.h: In constructor ‘ImGuiInputTextState::ImGuiInputTextState()’:
../../imgui_internal.h:620:84: error: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘struct ImGuiInputTextState’ with no trivial copy-assignment; use assignment or value-initialization instead [-Werror=class-memaccess]
  620 |     ImGuiInputTextState()                           { memset(this, 0, sizeof(*this)); }
      |                                                                                    ^
../../imgui_internal.h:600:18: note: ‘struct ImGuiInputTextState’ declared here
  600 | struct IMGUI_API ImGuiInputTextState
      |                  ^~~~~~~~~~~~~~~~~~~
../../imgui_internal.h: In constructor ‘ImGuiNextWindowData::ImGuiNextWindowData()’:
../../imgui_internal.h:781:64: error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct ImGuiNextWindowData’; use assignment or value-initialization instead [-Werror=class-memaccess]
  781 |     ImGuiNextWindowData()       { memset(this, 0, sizeof(*this)); }
      |                                                                ^
../../imgui_internal.h:764:8: note: ‘struct ImGuiNextWindowData’ declared here
  764 | struct ImGuiNextWindowData
      |        ^~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [Makefile:86: imgui.o] Error 1

**Reproduction steps**
Compile example_sdl_opengl3 with -Werror flag.

**Workaround**
There was a similar issue in #1822 and fix was included into imgui.cpp (~L1000). Current issue is that imgui_internal.h is included right before those pragmas. As a workaround, I can copy all pragmas into imgui.h and everything will compile.

Interestingly, there seem to be a smaller duplicated block of  pragmas in imgui_internal.h (L45) that does not include GCC pragmas.

**Comment by ocornut** [comment]
Thank you @inodlite for the details.

I've been trying to disable warnings on a strict per-need basis, hence the non-matching blocks. 

Added this specific block in imgui_internal.h now, could you confirm it compiles well? (my testing environments currently don't have GCC 9). Thanks!

Because we want user to include `imgui_internal.h` we don't rely in imgui\*\*.cpp files disabling warnings and include it before the block to disable warnings.

**Comment by inodlite** [comment]
Confirming that I can compile latest master with no issues.

Thank you for the quick fix and for your great software, @ocornut!

**Comment by ggerganov** [comment]
@ocornut I was building today an earlier version of Dear ImGui and ran across this compiler warning. I see it is being ignored since f242cd4, but am wondering if this is the correct thing to do here. Generally, memsetting a non-trivial structure could lead to problems on some compilers/platforms. What is your take on that - why not initialize those structures instead of using `memset`?

**Comment by ocornut** [comment]
@ggerganov I apologize but I don't have much energy to explain in details and be challenged on every technical decision at the moment. We favor zero-init and ImVector is designed to treat data as POD for performances reasons. If you or anyone comes with a proof that a problem _is_ happening with some compilers/platforms I'd hapilly revisit this but it hasn't been the case afaik and right now I don't see how it possibly could be a problem. Many of those new warnings are overzealous and make perfect sense for many/most projects but we're not most projects and have a low-level approach for many problems.
